// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLGbpfuihBBQNTLfpwHO9NAsiwckc8lY',
    appId: '1:761714612527:web:279c144939d486eda329da',
    messagingSenderId: '761714612527',
    projectId: 'kid-arena',
    authDomain: 'kid-arena.firebaseapp.com',
    storageBucket: 'kid-arena.firebasestorage.app',
    measurementId: 'G-V9EGBGGJ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnwNypnk9in6VBwNba2xBgOSCPHmYL_LM',
    appId: '1:761714612527:android:263fa8cec9a2f667a329da',
    messagingSenderId: '761714612527',
    projectId: 'kid-arena',
    storageBucket: 'kid-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwu9lGeN7PIWTeWigUZNi-rDSYBObExY',
    appId: '1:761714612527:ios:41706108038504aba329da',
    messagingSenderId: '761714612527',
    projectId: 'kid-arena',
    storageBucket: 'kid-arena.firebasestorage.app',
    iosBundleId: 'com.example.kidArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwu9lGeN7PIWTeWigUZNi-rDSYBObExY',
    appId: '1:761714612527:ios:41706108038504aba329da',
    messagingSenderId: '761714612527',
    projectId: 'kid-arena',
    storageBucket: 'kid-arena.firebasestorage.app',
    iosBundleId: 'com.example.kidArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKLGbpfuihBBQNTLfpwHO9NAsiwckc8lY',
    appId: '1:761714612527:web:e05aecc6d499577ca329da',
    messagingSenderId: '761714612527',
    projectId: 'kid-arena',
    authDomain: 'kid-arena.firebaseapp.com',
    storageBucket: 'kid-arena.firebasestorage.app',
    measurementId: 'G-GCRKCTJRBK',
  );

}